name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  conventional-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Set up gitlint
        run: |
          pip install gitlint

      - name: Check commits
        run: git log -1 --pretty=%B | gitlint --ignore B6

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Set up Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run black
        run: poetry run black --check src tests
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Set up Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run pylint
        run: poetry run pylint --fail-under=10 src tests

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Set up Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: poetry run pytest
